name: BungeeTp
description: Teleport across a BungeeCord network.

softdepend: [ Vault, Essentials, SuperVanish, PremiumVanish ]

author: SavageAvocado
website: savagedev.net

api-version: 1.13
main: net.savagedev.tpa.spigot.BungeeTpSpigotPlugin
version: ${version}
